<?php
namespace backend\controllers;
use backend\models\Menu;
use backend\models\SystemLog;
use common\components\Func;
use Yii;
use yii\helpers\Url;
use common\controllers\Controller;
use yii\filters\VerbFilter;
use backend\components\AccessControl;
use backend\models\Config;
use backend\widgets\ActiveForm;
use yii\web\Response;
class BaseController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','restore','captcha','authenticator','map'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                    'delete' => ['POST','GET'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function beforeAction($action)
    {
        if( $action->id === 'create' || $action->id === 'update' ){
            $this->layout = '_main_ajax';
        }
        //echo Yii::$app->request->csrfParam;exit;

        //$controller = Yii::$app->controller->id;
        $url        =  Yii::$app->requestedRoute; //当前访问 URL

        $controller =  Yii::$app->controller->id;
        $actionId   =  Yii::$app->controller->action->id;
        if($controller != 'system-log'){
        $menu   =  Menu::getMenu();
        $data   =  Func::array_column($menu,null,'url');
        if(isset($data[$url])){
            $info       = $data[$url]; //print_r($data);exit;
            if(isset($menu[$info['pid']]['name'])){
                $name   = $menu[$info['pid']]['name'];
            }else{
                $name   = $info['name'];
            }
            if($url == $controller .'/index'){
                if(Yii::$app->request->isPost){
                    $remark = '更新数据';
                }else{
                    $remark = '浏览数据';
                }
                $name   = $info['name'];

            }elseif($actionId == 'create'){
                $remark = '添加数据';

            }elseif($actionId == 'update'){
                $remark = '更新数据';

            }elseif($actionId == 'delete'){
                $remark = '删除数据';
            }elseif($actionId == 'view'){
                $remark = '浏览数据';
            }elseif($actionId == 'status'){
                $remark = '更新状态';
            }elseif($actionId == 'sort'){
                $remark = '更新排序';
            }else{
                $name   =  $info['name'];
                $remark = '更新数据';
            }
            if(Yii::$app->request->isPost || $actionId == 'delete') {
                SystemLog::log($name, $remark);
            }
        }else{
            $name   =   '未知';
            if(Yii::$app->request->isPost && $actionId != 'export' && $actionId != 'import' && $actionId !='restore'){
                $remark = '编辑数据';
                SystemLog::log($name,$remark);
            }
        }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * 初始化配置信息
     * 网站配置或模板配置等
     */
    public function init() {
        parent::init();
        Yii::$app->params['assetsUrl'] = (new \assets\backendAsset)->baseUrl;
        //$this->layout = '_main';
        Yii::$app->params['basic']      = Config::getConfigs('basic');
        Yii::$app->params['weixin']     = Config::getConfigs('weixin');
        Yii::$app->params['uploads']    = Config::getConfigs('uploads');
        Yii::$app->params['jifen']      = Config::getConfigs('jifen');
        //print_r(Yii::$app->params['uploads']);exit;
    }
    public function render($view, $params = [])
    {
        if(isset($params['model'])){
            $model = $params['model'];
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $data = ActiveForm::validate($model);
                if(!empty($data)){
                    return [
                        'status' => false,
                        'message'=>$data,
                    ];
                }
            }
        }

        return parent::render($view,$params);

    }
    /**
     * @param array|string $url
     * @param int $statusCode
     *
     *
     */
    public function redirect($url, $statusCode = 302)
    {
        if(Yii::$app->request->isAjax){
            $this->success('操作成功');exit;
        }else{
            return Yii::$app->getResponse()->redirect(Url::to($url), $statusCode);
        }
    }


    /*
     * 更新状态
     */
    public function actionStatus(){
        $id     = Yii::$app->request->post('id');
        $value  = Yii::$app->request->post('value');
        $name   = Yii::$app->request->post('name');
        if(empty($id))$this->error('请选择要操作的数据');
        if(!isset($name))$this->error('缺少字段参数');
        if(!isset($value))$this->error('缺少数据参数');
        $lists  = 0;
        $data   = (array) $id;
        foreach ($data as $val){
            $model  = $this->findModel($val);
            $model->{$name} = $value;
            $lists  += $model->save();
        }
        if(!empty($lists)){
            $this->success('操作成功');
        }else{
            $this->error('操作失败');
        }
    }
    /**
     *
     */
    public function actionSort(){
        $id     = Yii::$app->request->post('id');
        $value  = Yii::$app->request->post('value');
        $name   = Yii::$app->request->post('name');
        if(empty($id))$this->error('缺少ID参数');
        if(!isset($name))$this->error('缺少字段参数');
        if(!isset($value))$this->error('缺少数据参数');
        $model  = $this->findModel($id);
        $model->{$name} = $value;
        $lists  = $model->save();
        if($lists){
            $this->success('操作成功');
        }else{
            $this->error('操作失败');
        }
    }
}