<?php
namespace common\models;
use yii\behaviors\TimestampBehavior;
use Yii;



class CouponReceive extends \yii\db\ActiveRecord{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%coupon_receive}}';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name','trim'],
            [['uid','name'],'required'],
            [['type'],'required','message'=>'请选择{attribute}'],
            [['price','discount','min_price'],'required'],
            [['start_time','end_time'],'required'],
            [['id','uid','coupon_id','name','type','start_time','end_time','status','created_at','updated_at'], 'integer'],
            [['name',], 'string', 'max' => 50],
            [['price','min_price','discount'], 'double', ],
            [['type'], 'in', 'range' => [1, 2]],
            [['status'], 'in', 'range' => [0, 1, 2]],
            [['status'], 'default', 'value' => 1],

        ];
    }


    /**
     * @inheritdoc
     */

    public function attributeLabels()
    {
        return [
            'id'                => '领取ID',
            'uid'               => '用户UID',
            'coupon_id'         => '优惠券ID',
            'name'              => '优惠券名称',
            'type'              => '优惠券类型',//（1满减券、2折扣券）
            'price'             => '优惠金额',
            'discount'          => '折扣率',
            'min_price'         => '最低消费金额',
            'start_time'        => '开始时间',
            'end_time'          => '结束时间',
            'status'            => '状态',//（1有效,0已过期,2已使用）
            'created_at'        => '创建时间',
            'updated_at'        => '更新时间',
        ];
    }

    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/1/30 14:18
     */
    public function behaviors() {
        return [
            TimestampBehavior::className(),
        ];
    }

    public function scenarios()
    {
        $scenarios =  parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios['receive'] = [
            'uid','coupon_id','name','type','price','discount','min_price',
            'start_time','end_time','status','created_at','updated_at'
        ];
        $scenarios['status'] = ['id','status','updated_at'];
        return $scenarios;
    }


}
