<?php
namespace common\models;
use yii\behaviors\TimestampBehavior;
use Yii;



class OrderGoods extends \yii\db\ActiveRecord{
    const CACHE_KEY_FIND_DATA_MODEL = 'cache_key_order_goods_find_data_model';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%order_goods}}';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id','order_id','goods_id','image_id','deduct_stock_type','sku_id','quantity','created_at','updated_at'], 'integer'],
            [['sku_attr_id'], 'string', 'max' => 50],
            [['productcode'], 'string', 'max' => 100],
            [['title','sku_attr_name'], 'string', 'max' => 250],
            [['goods_weight','price','total_price'], 'double'],
            [['goods_id','image_id','deduct_stock_type','sku_id','goods_weight','price','total_price'], 'default', 'value' =>0],
            [['quantity','status'], 'default', 'value' =>1],
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                => '订单商品ID',
            'order_id'          => '订单ID',
            'goods_id'          => '商品ID',
            'title'             => '商品标题',
            'image_id'          => '商品图片',
            'deduct_stock_type' => '库存计算方式',
            'sku_id'            => 'sku规则ID',
            'sku_attr_id'       => 'sku属性ID',
            'sku_attr_name'     => 'sku属性',
            'productcode'       => '商品编码',
            'goods_weight'      => '商品重量',
            'price'             => '商品价钱',
            'quantity'          => '购买数量',
            'status'            => '状态', //状态(0已取消,1正常,2退款中,3已退款,4换货中,5已换货,6退款中,7已退款)
            'total_price'       => '商品总价',
            'created_at'        => '创建时间',
            'updated_at'        => '更新时间',
        ];
    }

/*
created_at		创建时间
updated_at		更新时间*/

    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/1/30 14:18
     */
    public function behaviors() {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * 保存之后执行
     * @param bool $insert
     * @param array $changedAttributes
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/4 14:11
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        //Yii::$app->cache->delete(self::CACHE_KEY_FIND_DATA_MODEL);
    }
    /**
     * @return array|mixed|\yii\db\ActiveRecord[]
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/4 14:11
     */
   /* public static function getFindDataList(){
        $key  = self::CACHE_KEY_FIND_DATA_MODEL;
        $data = Yii::$app->cache->get($key);
        if($data === false){
            $data = self::find()
                ->where("status=:status")
                ->addParams([':status'=>1])
                ->select("id,name,phone,detail")
                ->asArray()
                ->orderBy(['sort'=>SORT_ASC,'updated_at'=>SORT_DESC])
                ->all();

            Yii::$app->cache->set($key,$data);
        }
        if(empty($data)){
            return [];
        }
        return $data;
    }*/
    // 0已取消,1正常,2退款中,3已退款,4换货中,5已换货,6退款中,7已退款
    public static $status = [
        0 => '已取消',
        1 => '正常',
        2 => '退款中',
        3 => '已退款',
        4 => '换货中',
        5 => '已换货',
        6 => '退款中',
        7 => '已退款',
    ];
}
