<?php
namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;


class Region extends \yii\db\ActiveRecord{
    const CACHE_KEY_FIND_MODEL = 'cache_key_region_list_find_model';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%region}}';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id','parent_id'], 'integer'],
            [['name'], 'string', 'max' => 250],

        ];
    }



    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                => '地区ID',
            'name'              => '地区名称',
            'parent_id'         => '父节点ID',
        ];
    }
    public function save($runValidation = true, $attributeNames = null)
    {
        Yii::$app->cache->delete(self::CACHE_KEY_FIND_MODEL);
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $parentId
     * @return array|\yii\db\ActiveRecord[]
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/3 17:51
     */
    public static function getFindDataList($parentId=0)
    {
        $result = self::find()->where(['parent_id'=>$parentId])->indexBy('id')->asArray()->all();
        return $result;
    }
    /**
     * @param int $parentId
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/3 17:44
     */
    public static function getRegion($parentId=0)
    {
        $result = self::getFindDataList($parentId);
        $data   = ArrayHelper::map($result, 'id', 'name');
         return $data;
    }

    /**
     * 获取登陆信息
     * @return array|mixed|\yii\db\ActiveRecord[]
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/11 13:55
     */
    public static function getRegionAll(){
        $data = Yii::$app->cache->get(self::CACHE_KEY_FIND_MODEL);
        if($data === false){
        $data = self::find()
            ->select("id,name")
            ->asArray()
            ->all();
        $data   = ArrayHelper::map($data, 'id', 'name');
        Yii::$app->cache->set(self::CACHE_KEY_FIND_MODEL,$data);
        }
        return $data;
    }

}
