<?php
namespace backend\grid;
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
class CheckBoxColumn extends \yii\grid\ActionColumn {
    /**
     * {@inheritdoc}
     */
    public $header;
    public $attribute      = 'id';
    public $classOptions   = array();
    public $field           = 'id';
    /**
     * {@inheritdoc}
     */
    public function init()
    {
        if(!$this->header){
            $this->header =  Html::checkbox('all', false, ['class' => 'check-all', 'lay-skin' => 'primary', 'lay-filter' => 'check-all']);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    //开启或关闭 1开启 0关闭
    protected function renderDataCellContent($model, $key, $index)
    {

        $attribute =  $this->attribute;
        $options = array_merge([
            'class'=>'ids',
            'lay-skin'=>'primary',
            'value'=>$model[$attribute]
        ], $this->classOptions);

        return Html::checkbox($this->field.'[]',false,$options);

    }




}