<?php
namespace mobile\models;

use common\components\Func;
use common\models\OrderForm as common;
use Yii;



class Order extends common {


    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/8 12:08
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios['orderSubmit'] = [

        ];
        return $scenarios;
    }



    /**
     * amount 购买数量
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/9 17:23
     */
    public static function getFreight($delivery_id,$city_id=0,$amount=1,$first_fee = 0){
        //算出优惠
        $data = Delivery::getFreight($delivery_id,$city_id);
        if($first_fee<=0){
            $amount         =  ceil($amount/$data['first']);
            $first_fee      =  bcmul($amount,$data['first_fee'],2);
            $additional     =  $amount - $data['first'];
        }else{
            $additional     = $amount;
        }
        $additional     =  ceil($additional/$data['additional']);
        $additional_fee = bcmul($additional,$data['additional_fee'],2);
        $freight        =  bcadd($first_fee,$additional_fee,2);
        return $freight;
    }
    //End 算出运费







    /**
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/7 22:26
     */
    public function OrderSubmit(){


        $data = [
            'order_sn'          => self::getOrderSn(),
            'uid'               => 1,
            'discount_id'       => 0,
            'redbags_id'        => 0,
            'integral'          => 0,//积分抵消
            'unionId'           => 0,
            'delivery_type'     => 2,

            'extract_shop_id'   => 2, //自取ID
            'name'              => '李先生',//此方法只有 自取才可以生效
            'phone'             => '15977795537',//此方法只有 自取才可以生效

            'address_id'        => 0,//收货地址
            'shipping_price'    => 0,
            'remark'            => '自取才可以生效自取才可以生效',
            'goods'             => [
                [
                    'quantity'      => 2,//购买数量
                    'sku_id'        => 1,//购买SKU参数（只有库存）
                ],
                [
                    'quantity'      => 1,//购买数量
                    'sku_id'        => 2,//购买SKU参数（只有库存）
                ]
            ],
        ];


        $this->setAttributes($data);
        if($this->save()){
            echo 'OK';
        }else{
            print_r($this->getErrors());exit;
        }

    }
}
