<?php
namespace backend\models;

use Yii;

use common\models\Coupon as common;



class Coupon extends common
{
    public $rangedate;
    public function rules()
    {
        return [
            ['name','trim'],
            [['name'],'required'],
            [['type'],'required','message'=>'请选择{attribute}'],
            [['price','discount','min_price'],'required'],
            [['expire_type'],'required','message'=>'请选择{attribute}'],
            [['rangedate'],'required','message'=>'请选择{attribute}'],
            [['expire_day','start_time','end_time','amount','limit_amount','receive','sort'],'required'],

            [['id','type','expire_type','expire_day','start_time','end_time','amount','limit_amount','sort','status','created_at','updated_at'], 'integer'],
            [['name',], 'string', 'max' => 50],
            [['rangedate'], 'string', 'max' => 50],//时间范围
            [['price','min_price','discount'], 'double', ],
            [['sort'], 'default', 'value' => 50],
            [['status'], 'default', 'value' => 1],
            [['price','expire_day','discount','receive','start_time','end_time'], 'default', 'value' => 0],
            [['type','expire_type'], 'in', 'range' => [1, 2]],
            [['status'], 'in', 'range' => [0, 1]],

        ];
    }

    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/16 17:21
     */
    public function scenarios()
    {
        $scenarios =  parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios['typePriceday']      = ['name','type','price','min_price','expire_type','expire_day','amount','limit_amount','sort','status'];
        $scenarios['typeDiscountday']   = ['name','type','discount','min_price','expire_type','expire_day','amount','limit_amount','sort','status'];

        $scenarios['typePriceTime']      = ['name','type','price','min_price','expire_type','rangedate','amount','limit_amount','sort','status'];
        $scenarios['typeDiscountTime']   = ['name','type','discount','min_price','expire_type','rangedate','amount','limit_amount','sort','status'];
        return $scenarios;
    }
    public function beforeValidate()
    {
        if($this->type == 1 && $this->expire_type ==1){
            $this->scenario = 'typePriceday';
        }elseif($this->type == 2 && $this->expire_type ==1){
            $this->scenario = 'typeDiscountday';
        }elseif($this->type == 1 && $this->expire_type ==2){
            $this->scenario = 'typePriceTime';
        }elseif($this->type == 2 && $this->expire_type ==2){
            $this->scenario = 'typeDiscountTime';
        }

        if(empty($this->price)){
            $this->price = 0;
        }
        if(empty($this->discount)){
            $this->discount = 0;
        }
        if(empty($this->expire_day)){
            $this->expire_day = 3;
        }
        if($this->expire_type ==2){
            if(!empty($this->rangedate)){
                $attr = explode('~',$this->rangedate);
                $this->start_time = strtotime(trim($attr[0]));
                $this->end_time   = strtotime(trim($attr[1]));
            }

        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/16 17:21
     */
    public function attributeLabels(){
        $attributeLabels = parent::attributeLabels();
        $attributeLabels['rangedate'] = '时间范围';
        return $attributeLabels;
    }
    public static $status = [
      0 =>'禁用',
      1 =>'启用',
   ];

    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/15 22:41
     */
   public function getStatus(){
        return self::$status;
   }

    /**
     * @return mixed
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/15 22:41
     */
   public function getStatusText(){
       $data = self::$status;
       return $data[$this->status];
   }


    /**
     * @var array
     */
    public static $expire_type = [
        1 => '领取后生效',
        2 => '固定时间',
    ];
    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date DateTime
     */
    public function getExpireType(){
        return self::$expire_type;
    }

    /**
     * @return mixed
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/2/16 14:47
     */
    public function getExpireTypeText(){
        return self::$expire_type[$this->expire_type];
    }
}
