<?php
namespace backend\models;

use Yii;

use common\models\GoodsCategory as common;

class GoodsCategory extends common
{
        const CACHE_GOODS_KEY_LIST = 'cache_key_goods_list';
        const STATUS_ACTIVE = 1;
        const STATUS_DELETED = 0;
        /**
         * @var array
         */
        public static $status = [
            self::STATUS_ACTIVE => '启用',
            self::STATUS_DELETED => '禁止',
        ];

        /**
         * @return array
         * @Author 七秒记忆 <274397981@qq.com>
         * @Date 2020/1/17 11:58
         */
        public function getStatus(){
            return self::$status;
        }

        /**
         * @return mixed|string
         * @Author 七秒记忆 <274397981@qq.com>
         * @Date 2020/1/17 11:58
         */
        public function getStatusText(){
            if(isset(self::$status[$this->status])){
                return self::$status[$this->status];
            }else{
                return '--';
            }
        }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'trim'],
            [['name'], 'required'],
            [['parent_id'],'required','message'=>'请选择{attribute}'],

            [['id','parent_id','image_id','sort','is_delete','status' ,'created_at','updated_at'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['sort'], 'default', 'value' =>50],
            [['image_id','is_delete'], 'default', 'value' =>0],
            [['status'], 'default', 'value' =>1],

        ];
    }
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        Yii::$app->cache->delete(self::CACHE_GOODS_KEY_LIST);
    }

    /**
     * 后台选项
     * @return array|mixed|\yii\db\ActiveRecord[]
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/1/27 19:56
     */
    public static function getGoodsList(){
        $data = Yii::$app->cache->get(self::CACHE_GOODS_KEY_LIST);
        if($data === false){
        $data = self::find()
            ->where("status=:status and is_delete=:is_delete")
            ->addParams([':status'=>1,':is_delete'=>0])
            ->select("id,name,parent_id")
            ->orderBy(['sort'=>SORT_ASC,'id'=>SORT_ASC])
            ->asArray()
            ->all();
        Yii::$app->cache->set(self::CACHE_GOODS_KEY_LIST,$data);
        }
        return $data;
    }
}
