<?php
namespace backend\models;

use Yii;
use common\models\WxTplMsg as Common;
use yii\behaviors\TimestampBehavior;
/**
 * This is the model class for table "{{%wx_reply}}".

 */
class WxTplMsg extends Common
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),

        ];
    }
    /** scenarios
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title','template_sn'], 'required'],
            [['status','created_at','updated_at'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['remark'], 'string', 'max' => 255],
            [['template_id','template_sn'], 'string', 'max' => 64],
            ['status', 'default', 'value' =>0],
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        Yii::$app->cache->delete(Yii::$app->params['WX_TPL_MSG_KEY_CACHE']);
    }


}
